name: Build and Push Docker Image

env:
  IMAGE_NAME: quarkus-kotlin-ms-customer
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE_REF: ${{ env.DOCKER_USER }}/${{env.IMAGE_NAME}}:latest

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Verify dependencies
        run: ./gradlew help

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests and coverage
        run: ./gradlew test jacocoTestReport

      - name: Run SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_REF }} -f src/main/docker/Dockerfile.jvm .

      - name: Scan Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_REF }}
          format: 'table'
          severity: 'CRITICAL,HIGH'
        env:
          TRIVY_USERNAME: ${{ env.DOCKER_USER }}
          TRIVY_PASSWORD: ${{ env.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push ${{ env.DOCKER_USER }}/${{env.IMAGE_NAME}}:latest
