name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Set version env
        run: echo "VERSION=1.0.${{ github.run_number }}" >> $GITHUB_ENV
        
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Verify dependencies
        run: ./gradlew help

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests and coverage
        run: ./gradlew test jacocoTestReport

      - name: Run SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/quarkus-kotlin-ms-customer:1.0.${{ github.run_number }} -f src/main/docker/Dockerfile.jvm .

      - name: Scan Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/quarkus-kotlin-ms-customer:1.0.${{ github.run_number }}
          format: 'table'
          severity: 'CRITICAL,HIGH'
        env:
          TRIVY_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          TRIVY_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image - version -> 1.0.${{ github.run_number }}
        run: docker push ${{ secrets.DOCKER_USERNAME }}/quarkus-kotlin-ms-customer:1.0.${{ github.run_number }}

      - name: Push da imagem latest
        run: docker push ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_NAME }}:latest
